plugins {
    id "com.android.application"
}

android {
    namespace "com.postfinder.alerts"
    compileSdk 35

    signingConfigs {
        stable {
            storeFile file("postfinder-stable.jks")
            storePassword "pFbRAZ2xbbd_D6VrAIw78TSb7CVCoEzI"
            keyAlias "postfinder"
            keyPassword "pFbRAZ2xbbd_D6VrAIw78TSb7CVCoEzI"
        }
    }

    defaultConfig {
        applicationId "com.postfinder.alerts"
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName "1.5"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stable
        }
    }
}
